#!/bin/bash
# This is used by singcvmfs to execute cvmfs2 inside a container

if [ "$1" = "-o" ] && [ "$2" = "debug" ]; then
    if [ "${@:$#}" = "-f" ]; then
        # -f is added by singularity >= 3.6; remove it
        set -- "${@:1:$(($#-1))}"
    fi
    exec /usr/bin/cvmfs2 "$@"
fi
exec /usr/bin/cvmfs2 "$@" >/dev/null 2>&1
