#!/bin/bash
#
# Create the cvmfs dist directory, downloading the latest rpms from
#   the three major sources.
# Written by Dave Dykstra 17 April 2019
#

usage()
{
    (
    echo "Usage: makedist [-s] {osg|egi|default}"
    echo "       makedist [-s] -o <self_extracting_script>"
    echo " The first usage creates a distribution in 'dist' directory."
    echo " The second usage puts 'dist' and cvmfsexec tools into one script with the"
    echo "   given file name that self extracts and executes cvmfsexec."
    echo "   After extraction, files are left behind under '.cvmfsexec' in the same"
    echo "   directory as the script."
    echo " The -s option makes both operations work for cvmfssing instead"
    echo "   of cvmfsexec, and files are left in \$HOME/.cvmfssing"
    ) >&2
    exit 1
}

distroversion() {
    if [ -f /etc/os-release ]; then
        source /etc/os-release
        echo "${VERSION_ID/.*/}"
    elif [ -f /etc/redhat-release ]; then
        read LINE </etc/redhat-release
        case "$LINE" in
            *"release 6"*)
                echo "6"
                ;;
        esac
    fi
}

EL="`distroversion`"
ARCH="`arch`"

HERE="$(cd `dirname $0` && pwd)"

DIST="$HERE/dist"

SING=false
if [ "$1" = -s ]; then
    SING=true
    shift
fi
case $1 in
    -o)

        if [ $# != 2 ]; then
            usage
        fi
        if [ ! -d $DIST ]; then
            echo "$DIST not found" >&2
            exit 1
        fi
        BASENAME=cvmfsexec
        TOOLS="cvmfsexec mountrepo umountrepo"
        SEDOPTS=""
        if $SING; then
            BASENAME=cvmfssing
            TOOLS="cvmfssing"
            SEDOPTS="-e s/cvmfsexec/$BASENAME/ -e s/^BASEDIR=.*/BASEDIR=\$HOME/" 
        fi
        sed -e 's/^[ \t]*//' $SEDOPTS >$2 <<'!EOF!'
        #!/bin/bash
        BASEDIR="$(cd `dirname $0` && pwd)"
        BASE="$BASEDIR/.cvmfsexec"
        rm -rf $BASE
        mkdir $BASE
        TAR_START="`awk '/^__TAR_BELOW__/ {print NR + 1; exit 0; }' $0`"
        tail -n+$TAR_START $0 | tar -xzf - -C $BASE
        exec $BASE/cvmfsexec "$@"
        __TAR_BELOW__
!EOF!
        tar --exclude 'dist/var/run/cvmfs/*' --exclude 'dist/var/lib/cvmfs/*' -czvf - -C $HERE $TOOLS dist >>"$2"
        chmod +x "$2"
        exit
        ;;
    osg)
        if [ "$EL" = 6 ]; then
            REL=3.4
        else
            REL=3.5
        fi
        URL="https://repo.opensciencegrid.org/osg/$REL/el$EL/release/$ARCH";;
    egi)
        if [ "$EL" = 6 ]; then
            OS=sl6
        else
            OS=centos$EL
        fi
        URL="http://repository.egi.eu/sw/production/umd/4/$OS/$ARCH/updates";;
    default)
        URL="http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/$EL/$ARCH";;
    *) usage;;
esac

if [ -d $DIST ]; then
    echo "$DIST already exists" >&2
    exit 1
fi

LIST="`curl -Ls $URL/|grep "cvmfs-"|sed 's/.*href="//;s/".*//'`"
PKGS="`echo "$LIST"|grep "^cvmfs-[0-9]"|tail -1`"
PKGS="$PKGS `echo "$LIST"|grep "^cvmfs-config-$1-[0-9]"|tail -1`"
PKGS="$PKGS `echo "$LIST"|grep "^cvmfs-x509-helper-[0-9]"|tail -1`"

URLS=""
EPELPKGS=""
EPELURL="http://download.fedoraproject.org/pub/epel/$EL/$ARCH/Packages/f/"
if $SING; then
    PKGS="$PKGS `echo "$LIST"|grep "^cvmfs-fuse3-[0-9]"|tail -1`"
    EPELPKGS="`curl -Ls $EPELURL|grep fuse3-libs-[0-9]|sed 's/.*href="//;s/".*//'`"
fi

for PKG in $PKGS; do
    URLS="$URLS $URL/$PKG"
done
for PKG in $EPELPKGS; do
    URLS="$URLS $EPELURL/$PKG"
done

mkdir $DIST
cd $DIST
for U in $URLS; do
    echo "Extracting $U into $DIST"
    curl -Ls "$U"|rpm2cpio -|cpio -idmv
done

echo "./etc/cvmfs/default.local"
cat >etc/cvmfs/default.local <<!EOF!
CVMFS_HTTP_PROXY="auto;DIRECT"
CVMFS_PAC_URLS="http://cernvm-wpad.fnal.gov/wpad.dat;http://cernvm-wpad.cern.ch/wpad.dat"
!EOF!
