#!/bin/bash
# Run a singularity container including cvmfs repositories mounted
#   with the singularity --fusemount option.
# Written by Dave Dykstra March 2020

VERSION=3.1

ME="`basename $0`"

usage()
{
    echo "Usage: singcvmfs [-v] [command]"
    echo "       -v:   print current version and exit"
    echo "    command may contain whitespace"
    echo
    echo "Required environment variables:"
    echo " SINGCVMFS_REPOSITORIES  Comma-separated cvmfs repositories to mount"
    echo " SINGCVMFS_IMAGE         singularity container path or URL"
    echo
    echo "Optional environment variables:"
    echo " SINGCVMFS_CACHEDIR      Directory for the cvmfs cache"
    echo " SINGCVMFS_CVMFSOPTSFILE CVMFS options file (default.local)"
    echo "                           - must set at least CVMFS_HTTP_PROXY"
    echo " SINGCVMFS_SINGOPTS      Extra singularity options"
    exit 1
} >&2

HERE="$(cd `dirname $0` && pwd)"

ORIGPWD=$PWD

while getopts "v" OPTION; do
    case $OPTION in
        v)  echo "$VERSION"
            exit
            ;;
        ?)  shift $(($OPTIND-2))
            usage
            ;;
    esac
done
shift $(($OPTIND-1))

if [ ! -f $HERE/dist/usr/lib*/libcvmfs_fuse3.so ]; then
    echo "$ME: Must be run from where cvmfs distribution was made by 'makedist -s'" >&2
    exit 1
fi

if [ -z "$SINGCVMFS_REPOSITORIES" ]; then
    echo "$ME: SINGCVMFS_REPOSITORIES not set" >&2
    usage
    exit 1
fi

if [ -z "$SINGCVMFS_IMAGE" ]; then
    echo "$ME: SINGCVMFS_IMAGE not set" >&2
    usage
    exit 1
fi

REPOS="$SINGCVMFS_REPOSITORIES"
# Add the config repo if not already asked for
CONFIG_REPO="`grep -h '^CVMFS_CONFIG_REPOSITORY=' $HERE/dist/etc/cvmfs/default.d/*.conf 2>/dev/null|tail -1|sed 's/^CVMFS_CONFIG_REPOSITORY=//'`"
if [[ ",$REPOS," != *",$CONFIG_REPO,"* ]]; then
    REPOS="$CONFIG_REPO,$REPOS"
fi

declare -a MOUNT_ARGS
for R in ${REPOS//,/ }; do
    MOUNT_ARGS+=(--fusemount "\"container:cvmfs2 $R /cvmfs/$R\"")
done

cd $HERE/dist

if [ -n "$SINGCVMFS_CVMFSOPTSFILE" ]; then
    cp $SINGCVMFS_CVMFSOPTSFILE etc/cvmfs/default.local
fi

echo "CVMFS_NFILES=`ulimit -Hn`" >etc/cvmfs/default.d/00-nfiles.conf
echo "CVMFS_USYSLOG=/var/log/cvmfs/@fqrn@.log" >etc/cvmfs/default.d/00-usyslog.conf
LOGDIR=$HERE/log
mkdir -p $LOGDIR
SINGULARITY_BINDPATH="$SINGULARITY_BINDPATH,$LOGDIR:/var/log/cvmfs"

for P in `find * ! -type d ! -path '*/doc/*' ! -path 'var/lib/cvmfs/*'| \
        sed 's,/cvmfs/.*,/cvmfs,'|uniq`; do
    SINGULARITY_BINDPATH="$SINGULARITY_BINDPATH,$PWD/$P:/$P"
done
SINGULARITY_BINDPATH="${SINGULARITY_BINDPATH#,}" # remove leading comma
export SINGULARITY_BINDPATH

CACHEDIR=${SINGCVMFS_CACHEDIR:-$PWD/var/lib/cvmfs}

cd $ORIGPWD

exec singularity run -S /var/run/cvmfs -B $CACHEDIR:/var/lib/cvmfs \
    "${MOUNT_ARGS[@]}" ${SINGCVMFS_SINGOPTS[@]} $SINGCVMFS_IMAGE "$@"
