#!/bin/bash
#
# unmount cvmfs repositories that were mounted with mountrepo
# Written by Dave Dykstra 17 April 2019
#


usage()
{
    echo "Usage: umountrepo [-z] {repo.name|-a}" >&2
    exit 1
}

LAZY=false
if [ "$1" = "-z" ]; then
    LAZY=true
    shift
fi

if [ $# != 1 ]; then
    usage
fi

HERE="`dirname $0`"
if [ "$HERE" = "." ]; then
    HERE=$PWD
fi
DIST="$HERE/dist"

if [ "$1" = "-a" ]; then
    set -- `mount|grep " $DIST"|awk '{print $3}'`
else
    set -- $DIST/cvmfs/$1
fi

for REPO; do
    if $LAZY; then
        echo "Lazily unmounting $REPO"
        fusermount -uz $REPO
    else
        echo "Unmounting $REPO"
        fusermount -u $REPO
    fi
done
