#!/bin/bash -e
# Run docker as shown at
#  https://djw8605.github.io/2016/05/03/building-centos-packages-on-travisci/
#
# This more complicated setup is needed for github actions too because 
#  they do not provide a mechanism for reliably enabling user namespaces.
# Github actions does at least start a VM with docker already running.

# Assumes running on Ubuntu 24+

DOCKER_HUB_URI="$1"
docker pull "$DOCKER_HUB_URI"

DOCKER_CONTAINER_NAME="test_${OS_TYPE##*/}_${OS_VERSION//./_}"

set -x
docker run --privileged --network=host -v "$(pwd):/source:rw" \
  -e DOCKER_HUB_URI="$DOCKER_HUB_URI" \
  --name "$DOCKER_CONTAINER_NAME" "$DOCKER_HUB_URI" /bin/bash -exc \
	"cd /source && ./ci/privileged-run"

docker ps -a
docker stop "$DOCKER_CONTAINER_NAME"
docker rm -v "$DOCKER_CONTAINER_NAME"
