#!/bin/bash
# Now running as an unprivileged user with user namespaces enabled in a
# container and required packages installed. Make distributions and test.

. /etc/os-release

set -ex
if [ ! -f /usr/bin/fuse2fs ] && [ ! -f /usr/sbin/fuse2fs ]; then
    # skip fuse2fs tests
    CACHEPAT="/var/lib/cvmfs"
else
    truncate -s 6G scratch.img
    mkdir -p scratch/shared
    /sbin/mkfs.ext3 -F -O ^has_journal -d scratch scratch.img
    # for mode 4
    export SINGCVMFS_CACHEIMAGE=scratch.img
    CACHEPAT="/var/lib/cvmfs.*fuse"
fi
for DIST in default osg egi; do
    if [ "$DIST" = egi ] && ( [[ "$VERSION_ID" = 7* ]] || [[ "$VERSION_ID" = 8* ]] || [[ "$VERSION_ID" = 10* ]] || [ "$VERSION_ID" = 11 ] ); then
        # egi only supported on el9 and debian 12+
        continue
    fi
    if [ "$DIST" = osg ] && [[ "$VERSION_ID" = 7* ]]; then
        # osg not supported anymore for el7
        continue
    fi
    rm -rf dist /tmp/cvmfsexec
    : test makedist
    ./makedist $DIST
    : test mode 3
    ./cvmfsexec atlas.cern.ch -- ls /cvmfs/atlas.cern.ch/repo
    : test self-extracting distribution
    ./makedist -o /tmp/cvmfsexec
    if [ -f scratch.img ]; then
        /tmp/cvmfsexec -m $PWD/scratch.img atlas.cern.ch -- ls /cvmfs/atlas.cern.ch/repo /e2fs/lost+found
    else
        /tmp/cvmfsexec atlas.cern.ch -- ls /cvmfs/atlas.cern.ch/repo
    fi
    : test mode 1
    rm -rf dist/var/lib/cvmfs/shared
    ./mountrepo `cd dist/cvmfs; echo *config*`
    ./mountrepo atlas.cern.ch
    ls dist/cvmfs/atlas.cern.ch/repo
    if [[ "$ID" == *suse* ]]; then
        # the sle15 cvmfs suse build as of 2.11.5 does not support fuse3
        ./umountrepo -a
        continue
    fi
    : test mode 4
    if [ ! -d apptainer ]; then
        # get singularity or apptainer from oasis cvmfs
        ./mountrepo oasis.opensciencegrid.org
        if [[ "$VERSION_ID" == 7* ]]; then
            APPT=dist/cvmfs/oasis.opensciencegrid.org/mis/singularity/current
        else
            APPT=dist/cvmfs/oasis.opensciencegrid.org/mis/apptainer/current
        fi
        mkdir apptainer
        cp -r $APPT/`arch` $APPT/bin apptainer
    fi
    ./umountrepo -a
    rm -rf dist /tmp/cvmfsexec
    if [ "$ID" = debian ] || [ "$ID" = ubuntu ]; then
        # skip singcvmfs test on debian & ubuntu
        continue
    fi
    ./makedist -s $DIST
    ./makedist -s -o /tmp/cvmfsexec
    SINGCVMFS_REPOSITORIES=atlas.cern.ch PATH=$PATH:$PWD/apptainer/bin \
        ./singcvmfs exec -cip docker://$DOCKER_HUB_URI sh -c \
        "ls /cvmfs/atlas.cern.ch/repo && mount|grep $CACHEPAT"
    if [[ "$VERSION_ID" == 8* ]] || [[ "$VERSION_ID" == 9* ]]; then
        : try to at least make other supported architecture distributions
        EL=${VERSION_ID%.*}
        if [ "$DIST" = egi ] && [ "$EL" != 9 ]; then
            continue
        fi
        for arch in aarch64 ppc64le; do
            rm -rf dist /tmp/cvmfsexec
            ./makedist -m rhel$EL-$arch $DIST
            ./makedist -o /tmp/cvmfsexec
            rm -rf dist /tmp/cvmfsexec
            ./makedist -s -m rhel$EL-$arch $DIST
            ./makedist -s -o /tmp/cvmfsexec
        done
    fi
done
