#!/bin/bash
# Running in a privileged container.  Install required packages and
# switch to an unprivileged user to run the tests.

set -ex
if [ -f /usr/bin/zypper ]; then
    # suse
    zypper install -y tar gzip procps openssl-1_1 fuse fuse3 e2fsprogs
    if [[ $DOCKER_HUB_URI != *:15.5 ]]; then
        zypper install -y fuse2fs
    fi
elif [ -f /usr/bin/apt ]; then
    # debian or ubuntu
    apt-get update
    apt-get install -y procps curl rpm2cpio cpio fuse3 e2fsprogs fuse2fs 
else
    # rhel
    yum install -y procps-ng cpio findutils fuse fuse3 e2fsprogs
    if [[ $DOCKER_HUB_URI != *7* ]]; then
        yum install -y yum-utils
    fi
fi

# because host kernel is Ubuntu 24+, this enables user namespaces
sysctl kernel.apparmor_restrict_unprivileged_userns=0

# switch to an unprivileged user
useradd -u 1001 --create-home -s /bin/bash testuser
# leave .git as original owner for post job cleanup
chown testuser .
chown -R testuser *
su testuser -c ci/make-and-test
